services:
  mark:
    volumes:
      - ./mark/src:/opt/app
    #  - ./.envs/.env.mark.example:/opt/app/.env
    env_file:
      - ./.envs/.env.mark.example
    ports:
     - 8000:8000

  mark-migrations:
    volumes:
      - ./mark/src:/opt/app
    env_file:
      - ./.envs/.env.mark.example

  db:
    ports:
     - 5442:5432
    env_file:
      - ./.envs/.env.mark.example
