"""Add product_group

Revision ID: f09d13be11f7
Revises: b2cf6e1c1f29
Create Date: 2026-08-24 23:39:22.661705

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f09d13be11f7"
down_revision: Union[str, None] = "b2cf6e1c1f29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "product_group", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "product_group")
    # ### end Alembic commands ###
